global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    target_groups:
      - targets: ['localhost:9090']

  - job_name:       'src'
    scrape_interval: 5s

    target_groups:
      # src serve
      - targets: ['localhost:6060']

  - job_name: 'external_src'
    target_groups:
      # prometheus pushgateway
      - targets: ['localhost:9091']
