languageCode = "en-us"
title = "Documentation"
layoutDir = "docs/.layouts"
contentDir = "docs"

[params]
SectionOrder = ["getting-started", "install", "config", "concepts", "dev", "troubleshooting"]

[params.SectionNames]
getting-started = "Getting started"
install = "Installation"
config = "Configuration"
dev = "Development"
concepts = "Concepts"
troubleshooting = "Troubleshooting"
